# Generated by Django 4.1.3 on 2023-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('excel_file', models.FileField(upload_to='excel/')),
                ('pdf_file', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
